// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access_tokens.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessToken = `-- name: CreateAccessToken :one
INSERT INTO access_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, created_at, expires_at
`

type CreateAccessTokenParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error) {
	row := q.db.QueryRow(ctx, createAccessToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAccessToken = `-- name: DeleteAccessToken :exec
DELETE FROM access_tokens
WHERE id = $1
`

func (q *Queries) DeleteAccessToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccessToken, id)
	return err
}

const getAccessTokenByHash = `-- name: GetAccessTokenByHash :one
SELECT id, user_id, token_hash, created_at, expires_at FROM access_tokens
WHERE token_hash = $1
`

func (q *Queries) GetAccessTokenByHash(ctx context.Context, tokenHash string) (AccessToken, error) {
	row := q.db.QueryRow(ctx, getAccessTokenByHash, tokenHash)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listAccessTokensForUser = `-- name: ListAccessTokensForUser :many
SELECT id, user_id, token_hash, created_at, expires_at FROM access_tokens
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListAccessTokensForUser(ctx context.Context, userID uuid.UUID) ([]AccessToken, error) {
	rows, err := q.db.Query(ctx, listAccessTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessToken
	for rows.Next() {
		var i AccessToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
