// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	CreatedAt time.Time
	ExpiresAt pgtype.Timestamptz
}

type Repo struct {
	ID            uuid.UUID
	Owner         string
	Name          string
	Visibility    string
	DefaultBranch string
	CreatedAt     time.Time
}

type RepoPermission struct {
	UserID uuid.UUID
	RepoID uuid.UUID
	Level  string
}

type RepoPlacement struct {
	RepoID        uuid.UUID
	StorageNodeID string
}

type SshKey struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	PublicKey   string
	Fingerprint string
	CreatedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	Username  string
	CreatedAt time.Time
}
