// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repo_permissions.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getPermission = `-- name: GetPermission :one
SELECT user_id, repo_id, level FROM repo_permissions
WHERE user_id = $1 AND repo_id = $2
`

type GetPermissionParams struct {
	UserID uuid.UUID
	RepoID uuid.UUID
}

func (q *Queries) GetPermission(ctx context.Context, arg GetPermissionParams) (RepoPermission, error) {
	row := q.db.QueryRow(ctx, getPermission, arg.UserID, arg.RepoID)
	var i RepoPermission
	err := row.Scan(&i.UserID, &i.RepoID, &i.Level)
	return i, err
}

const grantPermission = `-- name: GrantPermission :one
INSERT INTO repo_permissions (user_id, repo_id, level)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, repo_id) DO UPDATE SET level = EXCLUDED.level
RETURNING user_id, repo_id, level
`

type GrantPermissionParams struct {
	UserID uuid.UUID
	RepoID uuid.UUID
	Level  string
}

func (q *Queries) GrantPermission(ctx context.Context, arg GrantPermissionParams) (RepoPermission, error) {
	row := q.db.QueryRow(ctx, grantPermission, arg.UserID, arg.RepoID, arg.Level)
	var i RepoPermission
	err := row.Scan(&i.UserID, &i.RepoID, &i.Level)
	return i, err
}

const listPermissionsForRepo = `-- name: ListPermissionsForRepo :many
SELECT user_id, repo_id, level FROM repo_permissions
WHERE repo_id = $1
`

func (q *Queries) ListPermissionsForRepo(ctx context.Context, repoID uuid.UUID) ([]RepoPermission, error) {
	rows, err := q.db.Query(ctx, listPermissionsForRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoPermission
	for rows.Next() {
		var i RepoPermission
		if err := rows.Scan(&i.UserID, &i.RepoID, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePermission = `-- name: RevokePermission :exec
DELETE FROM repo_permissions
WHERE user_id = $1 AND repo_id = $2
`

type RevokePermissionParams struct {
	UserID uuid.UUID
	RepoID uuid.UUID
}

func (q *Queries) RevokePermission(ctx context.Context, arg RevokePermissionParams) error {
	_, err := q.db.Exec(ctx, revokePermission, arg.UserID, arg.RepoID)
	return err
}
