// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repos.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (owner, name, visibility, default_branch)
VALUES ($1, $2, $3, $4)
RETURNING id, owner, name, visibility, default_branch, created_at
`

type CreateRepoParams struct {
	Owner         string
	Name          string
	Visibility    string
	DefaultBranch string
}

func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, createRepo,
		arg.Owner,
		arg.Name,
		arg.Visibility,
		arg.DefaultBranch,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRepo = `-- name: DeleteRepo :exec
DELETE FROM repos
WHERE id = $1
`

func (q *Queries) DeleteRepo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRepo, id)
	return err
}

const getRepo = `-- name: GetRepo :one
SELECT id, owner, name, visibility, default_branch, created_at FROM repos
WHERE id = $1
`

func (q *Queries) GetRepo(ctx context.Context, id uuid.UUID) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepo, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
	)
	return i, err
}

const getRepoByOwnerName = `-- name: GetRepoByOwnerName :one
SELECT id, owner, name, visibility, default_branch, created_at FROM repos
WHERE owner = $1 AND name = $2
`

type GetRepoByOwnerNameParams struct {
	Owner string
	Name  string
}

func (q *Queries) GetRepoByOwnerName(ctx context.Context, arg GetRepoByOwnerNameParams) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByOwnerName, arg.Owner, arg.Name)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.Visibility,
		&i.DefaultBranch,
		&i.CreatedAt,
	)
	return i, err
}
