// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repo_placement.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createPlacement = `-- name: CreatePlacement :one
INSERT INTO repo_placement (repo_id, storage_node_id)
VALUES ($1, $2)
RETURNING repo_id, storage_node_id
`

type CreatePlacementParams struct {
	RepoID        uuid.UUID
	StorageNodeID string
}

func (q *Queries) CreatePlacement(ctx context.Context, arg CreatePlacementParams) (RepoPlacement, error) {
	row := q.db.QueryRow(ctx, createPlacement, arg.RepoID, arg.StorageNodeID)
	var i RepoPlacement
	err := row.Scan(&i.RepoID, &i.StorageNodeID)
	return i, err
}

const deletePlacement = `-- name: DeletePlacement :exec
DELETE FROM repo_placement
WHERE repo_id = $1
`

func (q *Queries) DeletePlacement(ctx context.Context, repoID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlacement, repoID)
	return err
}

const resolvePlacement = `-- name: ResolvePlacement :one
SELECT repo_id, storage_node_id FROM repo_placement
WHERE repo_id = $1
`

func (q *Queries) ResolvePlacement(ctx context.Context, repoID uuid.UUID) (RepoPlacement, error) {
	row := q.db.QueryRow(ctx, resolvePlacement, repoID)
	var i RepoPlacement
	err := row.Scan(&i.RepoID, &i.StorageNodeID)
	return i, err
}
