// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ssh_keys.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createSSHKey = `-- name: CreateSSHKey :one
INSERT INTO ssh_keys (user_id, public_key, fingerprint)
VALUES ($1, $2, $3)
RETURNING id, user_id, public_key, fingerprint, created_at
`

type CreateSSHKeyParams struct {
	UserID      uuid.UUID
	PublicKey   string
	Fingerprint string
}

func (q *Queries) CreateSSHKey(ctx context.Context, arg CreateSSHKeyParams) (SshKey, error) {
	row := q.db.QueryRow(ctx, createSSHKey, arg.UserID, arg.PublicKey, arg.Fingerprint)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.Fingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSSHKey = `-- name: DeleteSSHKey :exec
DELETE FROM ssh_keys
WHERE id = $1
`

func (q *Queries) DeleteSSHKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSSHKey, id)
	return err
}

const getSSHKeyByFingerprint = `-- name: GetSSHKeyByFingerprint :one
SELECT id, user_id, public_key, fingerprint, created_at FROM ssh_keys
WHERE fingerprint = $1
`

func (q *Queries) GetSSHKeyByFingerprint(ctx context.Context, fingerprint string) (SshKey, error) {
	row := q.db.QueryRow(ctx, getSSHKeyByFingerprint, fingerprint)
	var i SshKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.Fingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const listSSHKeysForUser = `-- name: ListSSHKeysForUser :many
SELECT id, user_id, public_key, fingerprint, created_at FROM ssh_keys
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListSSHKeysForUser(ctx context.Context, userID uuid.UUID) ([]SshKey, error) {
	rows, err := q.db.Query(ctx, listSSHKeysForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SshKey
	for rows.Next() {
		var i SshKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PublicKey,
			&i.Fingerprint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
